version: '3.1'

services:

  db:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017

  app:
    build: .
    container_name: app_clientes
    restart: always
    ports:
      - 5050:5000
    environment:
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
